### ISSUE TITLE
Query function: build artifact metadata

### ISSUE THREAD

**Issue by mxmxchere** [gardenlinux/python-gardenlinux-lib#1]
It is planned to extend the `info.yaml` format in a way that it will contain a list of generated build artifacts. This information should be exposed so that it can be used by gl-oci.

**Comment by Vincinator** [comment]
Implemented [get_oci_metadata](https://github.com/gardenlinux/python-gardenlinux-lib/blob/2d0db0fffc717adbd043b7d589b58b259f49fea6/src/python_gardenlinux_lib/features/parse_features.py#L96) function to return information required by deducing media types based on cname.

- based on cname we get the list of all features
- for each feature, we check if an `image.<filetype>` or `convert.<filetype>` file exists in that folder
- if such a file exists, we adapt layer information to have the right media type for <filetype>
- if such a file does not exist, defaults of `.raw` and `.tar` mediatypes are assumed 

Task is done, however, after completion of initial delivery we can talk about refactoring to a query based approach if required
